"""added timers to recipe instructions

Revision ID: 3d3e6bfa01c9
Revises: 4395a04f7784
Create Date: 2026-04-16 09:14:35.639677

"""

from datetime import datetime
from uuid import uuid4

import dateparser.search
import sqlalchemy as sa
from sqlalchemy import orm

from alembic import op
from mealie.core.root_logger import get_logger
from mealie.db.models._model_utils.guid import GUID
from mealie.db.models.recipe.timer import RecipeTimerModel
from mealie.services.parser_services.parser_utils.duration_parser import DurationParser


import mealie.db.migration_types

# revision identifiers, used by Alembic.
revision = "3d3e6bfa01c9"
down_revision: str | None = "4395a04f7784"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None

logger = get_logger()


# Intermediate table definitions
class SqlAlchemyBase(orm.DeclarativeBase):
    pass


class RecipeInstruction(SqlAlchemyBase):
    __tablename__ = "recipe_instructions"

    id: orm.Mapped[GUID] = orm.mapped_column(GUID, primary_key=True, default=GUID.generate)
    recipe_id: orm.Mapped[GUID | None] = orm.mapped_column(GUID, index=True)
    text: orm.Mapped[str | None] = orm.mapped_column(sa.String, index=True)
    timers: orm.Mapped[list["RecipeTimerModel"]] = orm.relationship("RecipeTimerModel", single_parent=True)


def parse_instructions(session: orm.Session):
    SAMPLE_SIZE = 20

    # Fetch one instruction for each recipe
    distinct_recipe_ids = session.query(RecipeInstruction.recipe_id).distinct().limit(SAMPLE_SIZE).subquery()

    instruction_samples = (
        session.query(RecipeInstruction)
        .join(distinct_recipe_ids, RecipeInstruction.recipe_id == distinct_recipe_ids.c.recipe_id)
        .filter(RecipeInstruction.text.isnot(None), RecipeInstruction.text != "")
        .distinct(RecipeInstruction.recipe_id)
        .limit(SAMPLE_SIZE)
        .all()
    )

    # Extract the languages from each instruction
    results: list[list[tuple[str, datetime, str]]] = [
        dateparser.search.search_dates(instruction.text, add_detected_language=True)  # type: ignore
        for instruction in instruction_samples
        if instruction.text
    ]

    languages = {"en"}
    for result in results:
        if not result:
            continue

        for _, _, lang in result:
            languages.add(lang)

    # Parse all instructions using the detected languages
    logger.info(f"Detected languages: {languages}")

    timers_data: list[dict] = []
    duration_parser = DurationParser()
    for instruction in session.query(RecipeInstruction).all():
        if not instruction.text:
            continue

        timers = duration_parser.get_all_durations(instruction.text, languages=languages)

        for timer in timers:
            timers_data.append({"id": uuid4(), "duration": timer, "recipe_instruction_id": instruction.id})

    op.bulk_insert(RecipeTimerModel.__table__, timers_data)
    session.commit()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipe_timers",
        sa.Column("id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("recipe_instruction_id", mealie.db.migration_types.GUID(), nullable=True),
        sa.Column("created_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["recipe_instruction_id"],
            ["recipe_instructions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recipe_timers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_recipe_timers_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_recipe_timers_recipe_instruction_id"), ["recipe_instruction_id"], unique=False
        )

    # ### end Alembic commands ###

    bind = op.get_bind()
    session = orm.Session(bind=bind)

    try:
        logger.info("Parsing instruction timers")
        parse_instructions(session)
    except Exception:
        logger.exception("Failed to parse instruction timers; continuing with migration anyway")
        session.rollback()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipe_timers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recipe_timers_recipe_instruction_id"))
        batch_op.drop_index(batch_op.f("ix_recipe_timers_created_at"))

    op.drop_table("recipe_timers")
    # ### end Alembic commands ###
