"""Added a new webhookType timer 'for' groupWebhook

Revision ID: 04518927c8f8
Revises: a1b2c3d4e5f6
Create Date: 2026-04-19 22:59:13.276303

"""

import sqlalchemy as sa
from alembic import op

import mealie.db.migration_types

# revision identifiers, used by Alembic.
revision = "04518927c8f8"
down_revision: str | None = "a1b2c3d4e5f6"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("webhook_urls", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", mealie.db.migration_types.GUID(), nullable=True))
        batch_op.add_column(sa.Column("timer_event", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("is_deep_link", sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f("ix_webhook_urls_user_id"), ["user_id"], unique=False)
        batch_op.create_foreign_key("fk_webhook_urls_user_id_users", "users", ["user_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("webhook_urls", schema=None) as batch_op:
        batch_op.drop_constraint("fk_webhook_urls_user_id_users", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_webhook_urls_user_id"))
        batch_op.drop_column("is_deep_link")
        batch_op.drop_column("timer_event")
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###
