"""'add primary unit system and preparation instruction relation'

Revision ID: c8b3ed6e8fc4
Revises: 6f4d2c9b1eaa
Create Date: 2026-05-04 08:14:13.288414

"""

import sqlalchemy as sa
from alembic import op

import mealie.db.migration_types

# revision identifiers, used by Alembic.
revision = "c8b3ed6e8fc4"
down_revision: str | None = "6f4d2c9b1eaa"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipe_instructions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("preparation_instruction_id", mealie.db.migration_types.GUID(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_recipe_instructions_preparation_instruction_id"),
            ["preparation_instruction_id"],
            unique=False,
        )
        batch_op.create_foreign_key(
            "fk_recipe_instructions_preparation_instruction_id",
            "recipe_instructions",
            ["preparation_instruction_id"],
            ["id"],
        )

    with op.batch_alter_table("recipes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("primary_unit_system", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipes", schema=None) as batch_op:
        batch_op.drop_column("primary_unit_system")

    with op.batch_alter_table("recipe_instructions", schema=None) as batch_op:
        batch_op.drop_constraint("fk_recipe_instructions_preparation_instruction_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_recipe_instructions_preparation_instruction_id"))
        batch_op.drop_column("preparation_instruction_id")

    # ### end Alembic commands ###
