"""added active timers to recipe instruction

Revision ID: 164d1cb34958
Revises: 3d3e6bfa01c9
Create Date: 2026-04-18 01:12:44.492811

"""

import sqlalchemy as sa
from alembic import op

import mealie.db.migration_types

# revision identifiers, used by Alembic.
revision = "164d1cb34958"
down_revision: str | None = "3d3e6bfa01c9"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipe_timers_active",
        sa.Column("id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("complete_time", mealie.db.migration_types.NaiveDateTime(), nullable=False),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("recipe_id", mealie.db.migration_types.GUID(), nullable=True),
        sa.Column("recipe_timer_id", mealie.db.migration_types.GUID(), nullable=True),
        sa.Column("household_id", mealie.db.migration_types.GUID(), nullable=True),
        sa.Column("group_id", mealie.db.migration_types.GUID(), nullable=True),
        sa.Column("user_id", mealie.db.migration_types.GUID(), nullable=True),
        sa.Column("created_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recipe_timer_id"],
            ["recipe_timers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recipe_timers_active", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_recipe_timers_active_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_recipe_timers_active_group_id"), ["group_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_recipe_timers_active_household_id"), ["household_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_recipe_timers_active_recipe_id"), ["recipe_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_recipe_timers_active_recipe_timer_id"),
            ["recipe_timer_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_recipe_timers_active_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipe_timers_active", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recipe_timers_active_user_id"))
        batch_op.drop_index(batch_op.f("ix_recipe_timers_active_recipe_timer_id"))
        batch_op.drop_index(batch_op.f("ix_recipe_timers_active_recipe_id"))
        batch_op.drop_index(batch_op.f("ix_recipe_timers_active_household_id"))
        batch_op.drop_index(batch_op.f("ix_recipe_timers_active_group_id"))
        batch_op.drop_index(batch_op.f("ix_recipe_timers_active_created_at"))

    op.drop_table("recipe_timers_active")
    # ### end Alembic commands ###
