"""added my custom columns

Revision ID: abf60f8d604f
Revises: 04518927c8f8
Create Date: 2026-04-28 10:20:53.177339

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "abf60f8d604f"
down_revision: str | None = "04518927c8f8"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ingredient_foods", schema=None) as batch_op:
        batch_op.add_column(sa.Column("density", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("tip", sa.String(), nullable=True))

    with op.batch_alter_table("ingredient_units", schema=None) as batch_op:
        batch_op.add_column(sa.Column("position", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("range", sa.JSON(), nullable=True))

    with op.batch_alter_table("multi_purpose_labels", schema=None) as batch_op:
        batch_op.add_column(sa.Column("label_text", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("position", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("place", sa.String(), nullable=True))

    with op.batch_alter_table("tools", schema=None) as batch_op:
        batch_op.add_column(sa.Column("position", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("label_text", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("weight", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("serving_category", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tools", schema=None) as batch_op:
        batch_op.drop_column("serving_category")
        batch_op.drop_column("weight")
        batch_op.drop_column("label_text")
        batch_op.drop_column("position")

    with op.batch_alter_table("multi_purpose_labels", schema=None) as batch_op:
        batch_op.drop_column("place")
        batch_op.drop_column("position")
        batch_op.drop_column("label_text")

    with op.batch_alter_table("ingredient_units", schema=None) as batch_op:
        batch_op.drop_column("range")
        batch_op.drop_column("position")

    with op.batch_alter_table("ingredient_foods", schema=None) as batch_op:
        batch_op.drop_column("tip")
        batch_op.drop_column("density")

    # ### end Alembic commands ###
