"""Made changes to unit.range

Revision ID: 5fff42642462
Revises: a1f4c2d9e8b3
Create Date: 2026-06-07 05:21:39.390092

"""

import sqlalchemy as sa
from alembic import op

from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = "5fff42642462"
down_revision: str | None = "a1f4c2d9e8b3"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ingredient_units", schema=None) as batch_op:
        batch_op.add_column(sa.Column("rangeStart", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("rangeStart2", sa.Float(), nullable=True))
        batch_op.drop_column("range")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ingredient_units", schema=None) as batch_op:
        batch_op.add_column(sa.Column("range", sqlite.JSON(), nullable=True))
        batch_op.drop_column("rangeStart2")
        batch_op.drop_column("rangeStart")

    # ### end Alembic commands ###
